### ISSUE TITLE
JS Error in Commonjs ENV

### ISSUE THREAD

**Issue by gaoyuan1223m** [buxlabs/abstract-syntax-tree#104]
your lib throws an error here, any updating schedule?
![js error ast](https://user-images.githubusercontent.com/40973672/124101718-38535d80-da92-11eb-8cc4-1e7b1bb8481f.png)

**Comment by emilos** [comment]
hey @gaoyuan1223m, thanks for checking it out. Please note that the lib requires at least node14. You can see it here:

https://github.com/buxlabs/abstract-syntax-tree/blob/master/package.json#L15

I have no plans to support older versions, sorry about that.
