### ISSUE TITLE
Type Literal instead of BigIntLiteral

### ISSUE THREAD

**Issue by Tc14Hd** [buxlabs/abstract-syntax-tree#111]
The code
```
tree = ast.parse("1000000000000000n");
console.log(tree.body[0].expression);
```
outputs a node of type "Literal": 
```
{
  type: 'Literal',
  value: 1000000000000000n,
  bigint: '1000000000000000'
}
```
But the [README](https://github.com/buxlabs/abstract-syntax-tree#nodes) implies that the type should rather be "BigIntLiteral". Is this a bug?

**Comment by emilos** [comment]
@Tc14Hd thanks! That's a bug in the readme, not intentional. I've removed the falsy example.
