### ISSUE TITLE
Update badges

### ISSUE THREAD

**Issue by emilos** [buxlabs/abstract-syntax-tree#79]
They should point at the github ci

**Comment by Emmanuella-Aninye** [comment]
I would like to find out more information about this issue thanks.

**Comment by emilos** [comment]
Hey @Emmanuella-Aninye  the README has badges that are pointing to old continous integration environment (they are out of date).

We'd like to:

1) remove coverage badge
2) replace build passing badge with one that points to github (example here, line 4 https://raw.githubusercontent.com/buxlabs/pure-engine/master/README.md)

Thanks!

**Comment by Emmanuella-Aninye** [comment]
Sounds good I would like to take the task
