### ISSUE TITLE
Remove the comparify dependency in favor of own code

### ISSUE THREAD

**Issue by emilos** [buxlabs/abstract-syntax-tree#81]
The library is not maintained and the code seems fairly simple, so let's rewrite it slightly to become a part of the library.

## Acceptance criteria

- [x] remove the dependency
- [x] new code that passes all existing specs
- [ ] add new specs

```js
const comparify = require('comparify')

module.exports = function equal (node1, node2) {
  return comparify(node1, node2)
}
```

**Comment by alexfernandez** [comment]
This is already implemented, I think? :thinking:

**Comment by emilos** [comment]
@alexfernandez yes, but the specs are missing :)
