### ISSUE TITLE
Add Meriyah's wiki table to this module's readme?

### ISSUE THREAD

**Issue by drolsen** [buxlabs/abstract-syntax-tree#84]
Hey emilo, back at it with my favorite AST plugin ;) and I noticed the switch to Meriyah.
Compaired to cherow, Meriyah took me longer than I would like to admit to find its valid tree types:

https://github.com/meriyah/meriyah/wiki/ESTree-Node-Types-Table

Could we add this link to this plugin's readme, so returning and new users have a quicker way to find this table? I tend to cling to this list as I use this module's `find` method and I'm sure others would too.

Thanks again emilo!

**Comment by emilos** [comment]
hey @drolsen thanks for having a look again :). I think it makes sense, we could either link to it and/or port it over. PRs welcome as usual!

**Comment by emilos** [comment]
hey @drolsen I've added a similar table, is it good enough? Thanks!
