### ISSUE TITLE
Cannot find module ‘./types.json’

### ISSUE THREAD

**Issue by markpanado** [buxlabs/abstract-syntax-tree#88]
The npm package 2.9.0 has missing files... We are having this error:

![IMG_5538](https://user-images.githubusercontent.com/3646720/90850992-eb98f380-e3a5-11ea-8552-10ff98e6df2d.jpeg)

**Comment by emilos** [comment]
hey @markpanado thanks for the bug report. That's interesting, because the build passes locally and in the CI. I'll have a look.

In the meantime, how are you using the library?

**Comment by emilos** [comment]
@markpanado I've found the issue, I've forgot to specify the new file in `package.json`. Version `2.9.3` is working. Thanks!
