### ISSUE TITLE
Async methods

### ISSUE THREAD

**Issue by emilos** [buxlabs/abstract-syntax-tree#89]
## Story

As a developer, I want to have async methods, like `replaceAsync`

## Acceptance criteria

- [ ] replaceAsync
- [ ] findAsync
- [ ] ...

**Comment by inikonorov** [comment]
just wrap functions in promises?) f.e. 
`return new Promise((resolve, reject) => {
    // ..function code
    resolve()
    // or if occured any mistake
    reject()
})`

**Comment by emilos** [comment]
@inikonorov that would be a good start :) long term, I'd like to make async functions a bit more flexible, but it's not necessary for this issue
