### ISSUE TITLE
 dynamic imports will generate error

### ISSUE THREAD

**Issue by Jeromy-L** [buxlabs/abstract-syntax-tree#96]
source code  :
import('.a').then(function(b) {
        b.doSomething();
})
use parse function to change into ast
and then i  change this ast to code will get error

it can parse ast but can not generate into code 
it just use the parse to change this code to  ast but will get errors when use generate function, just same code

**Comment by emilos** [comment]
@Jeromy-L thanks for the bug report, I've added a test case and code to support it. `astring` has a PR that adds it, but it wasn't merged yet. It should be available in version `2.14.0`.
